package me.neobliz1.ecomonitoring.platform.analysis.infrastructure.adapter.inbound.web.doc;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Map;

@Schema(
        name = "WeatherMapResponse",
        description = "Complete spatial weather matrix structure output generated by processing time-slice intervals"
)
public record WeatherMapResponse(
        @Schema(
                name = "timestamp_bucket",
                description = "Aligned active timestamp aggregation bucket floor unix marker milliseconds",
                example = "1718845200000"
        )
        long timestampBucket,

        @Schema(
                name = "interval_minutes",
                description = "Configured computation range bucket time slice duration calculated in minutes",
                example = "15"
        )
        int intervalMinutes,

        @Schema(
                name = "grid_cells",
                description = "Geospatial coordinate grid cell layer dictionary index tracking calculated climatic fields. "+
                        "The dictionary entry keys represent spatial coordinate string identifiers (e.g. Geohashes).",
                example = "{\"v1234\": {\"geohash\": \"v1234\", \"reading_count\": 12, \"avg_temperature\": 22.5, \"avg_humidity\": 45.2, \"avg_pressure\": 1013.2, \"avg_pm25\": 12.4, \"avg_noise_db\": 42.1}}"
        )
        Map<String, GridCellLayersDoc> gridCells
) {
}