receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  jaeger_storage_exporter:
    trace_storage: my_memory_store

extensions:
  jaeger_storage:
    backends:
      my_memory_store:
        memory:
          max_traces: 20000

  jaeger_query:
    storage:
      traces: my_memory_store

service:
  extensions: [ jaeger_storage, jaeger_query ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ ]
      exporters: [ jaeger_storage_exporter ]
