---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  show-actuator: false
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    use-root-path: true

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false