services:
  vector-sidecar:
    image: timberio/vector:0.56.0-alpine
    ports:
      - "6000:6000"
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - vector_disk_buffer:/var/lib/vector/buffer
    networks:
      - eco-net
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully
    restart: on-failure
    environment:
      KAFKA_USER: ${KAFKA_ADMIN}
      KAFKA_PASSWORD: ${KAFKA_ADMIN_PASSWORD}
      VECTOR_LOG: "info"
