services:
  vector-storage-init:
    # image: redis:8.8.0-alpine
    image: redis@sha256:9d317178eceac8454a2284a9e6df2466b93c745529947f0cd42a0fa9609d7005
    user: "0:0"
    volumes:
      - vector_disk_buffer:/var/lib/vector:rw
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        chown -R 100:1000 /var/lib/vector
        chmod -R 0700 /var/lib/vector
        echo "🔒 Host persistent vector disk buffer layer successfully hardened to 0700 (100:1000)!"

  vector-vault-init:
    # image: hashicorp/vault:2.0.0
    image: hashicorp/vault@sha256:e40c741ed95bb271425e3e6ca6c222d620cf8682f6f7a1b1e7c9d49d0aba484b
    user: "100:1000"
    depends_on:
      vault-server:
        condition: service_healthy
      vault-init:
        condition: service_completed_successfully
    networks:
      - eco-net
    volumes:
      - ../vault/config/vector-agent.hcl:/etc/vault/agent.hcl:ro
      - vault_tokens:/tmp/vault_input:rw
      - ram_secrets_vector:/run/secrets
    entrypoint: [ "sh", "-c" ]
    command: [ "vault agent -exit-after-auth -config=/etc/vault/agent.hcl" ]

  vector-sidecar:
    # image: timberio/vector:0.56.0-alpine
    image: timberio/vector@sha256:8f2de273559680c4a6a03bb2bcf4a7636b08e0fb15269f546adc7b2cef2b6e8c
    ports:
      - "6000:6000"
      - "6001:6001"
      - "9598:9598"
    networks:
      - eco-net
    user: "100:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - ./run-vector.sh:/usr/local/bin/run-vector.sh:ro
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - vector_disk_buffer:/var/lib/vector:rw
      - ram_secrets_vector:/run/secrets:rw
    environment:
      VECTOR_LOG: "info"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "nc -z -w 1 127.0.0.1 9598 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 5
    entrypoint: [ "sh", "-c" ]
    command: [ "/usr/local/bin/run-vector.sh" ]