include:
  - ./compose/kafka.yaml
  - ./compose/schema-registry.yaml
  - ./compose/consul.yaml
  - ./compose/jaeger.yaml
  - ./compose/redis.yaml
  - ./compose/postgres.yaml
  - ./compose/vector/vector-sidecar.yaml
  - ./compose/clickhouse.yaml
  - ./compose/grafana.yaml

volumes:
  vector_disk_buffer:
    driver: local
  postgres_persistence_file:

secrets:
  kafka_server_jaas:
    file: secrets/scram/kafka_server_jaas.conf
  schema_registry_jaas:
    file: secrets/scram/schema_registry_jaas.conf
  redis_password:
    file: secrets/redis/redis_password
  postgres_password:
    file: secrets/postgres/postgres_password
  eco_user_password:
    file: secrets/postgres/eco_user_password

networks:
  eco-net:
    driver: bridge