include:
  - ./compose/kafka.yaml
  - ./compose/schema-registry.yaml
  - ./compose/history-test/consul.yaml
  - ./compose/history-test/postgres.yaml

volumes:
  vector_disk_buffer:
    driver: local

secrets:
  kafka_server_jaas:
    file: secrets/scram/kafka_server_jaas.conf
  schema_registry_jaas:
    file: secrets/scram/schema_registry_jaas.conf
  postgres_password:
    file: secrets/redis/postgres_password

networks:
  eco-net:
    driver: bridge