sources:
  grpc_sensor_in:
    type: "vector"
    address: "0.0.0.0:6000"

transforms:
  extract_pure_bytes:
    type: "remap"
    inputs: [ "grpc_sensor_in" ]
    source: |
      # 1. Vector encodes the incoming gRPC ByteString into a Base64 string internally.
      # 2. Decode it back to raw binary bytes and place it in the root message field.
      .message = decode_base64!(.raw_protobuf_packet)

sinks:
  kafka_out:
    type: "kafka"
    inputs: [ "extract_pure_bytes" ]
    bootstrap_servers: "kafka:9092"
    topic: "environment.weather.telemetry.live"
    encoding:
      codec: "raw_message"

    sasl:
      enabled: true
      mechanism: "SCRAM-SHA-512"
      username: ${KAFKA_USER}
      password: ${KAFKA_PASSWORD}

    buffer:
      type: "disk"
      max_size: 5368709120
      when_full: "block"