spring:
    profiles:
        # profile for include common configs from common-core module
        include: common
    application:
        name: ${SPRING_INGESTION_APPLICATION_NAME}
    config:
        import: "optional:consul:${SPRING_CLOUD_CONSUL_HOST}:${SPRING_CLOUD_CONSUL_PORT}/"
    cloud:
        consul:
            host: ${SPRING_CLOUD_CONSUL_HOST}
            port: ${SPRING_CLOUD_CONSUL_PORT}
            discovery:
                enabled: true
                prefer-ip-address: true
                ip-address: ${SERVER_HOST}
                port: ${INGESTION_APPLICATION_SERVER_PORT}
                service-name: ${SPRING_INGESTION_APPLICATION_NAME}
                health-check-path: /actuator/health
                health-check-interval: 10s
            config:
                enabled: true
                format: yaml
                prefixes: config

server:
    port: ${INGESTION_APPLICATION_SERVER_PORT}
