services:
  postgres-vault-init:
    # image: hashicorp/vault:2.0.0
    image: hashicorp/vault@sha256:e40c741ed95bb271425e3e6ca6c222d620cf8682f6f7a1b1e7c9d49d0aba484b
    user: "100:1000"
    depends_on:
      vault-server:
        condition: service_healthy
      vault-init:
        condition: service_completed_successfully
    volumes:
      - ../vault/config/postgres-agent.hcl:/etc/vault/agent.hcl:ro
      - vault_tokens:/tmp/vault_input:rw
      - ram_secrets_postgres:/run/secrets
    networks:
      - eco-net
    entrypoint: [ "sh", "-c" ]
    command: [ "vault agent -exit-after-auth -config=/etc/vault/agent.hcl" ]

  pg-db-init:
    # image: postgres:18.4-alpine3.24
    image: postgres@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    networks:
      - eco-net
    volumes:
      - postgres_persistence_file:/var/lib/postgresql/data
      - ./pg-db-init.sh:/usr/local/bin/init-postgres.sh:ro
      - ram_secrets_postgres:/run/secrets:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_SCHEMA: ${POSTGRES_DB_SCHEMA}
      PGDATA: ${PGDATA}
    entrypoint: [ "sh", "-c" ]
    command: [ "/usr/local/bin/init-postgres.sh" ]

  pg-db:
    # image: postgres:18.4-alpine3.24
    image: postgres@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    depends_on:
      pg-db-init:
        condition: service_completed_successfully
    user: "999:999"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - "5432:5432"
    volumes:
      - postgres_persistence_file:/var/lib/postgresql/data
    networks:
      - eco-net
    environment:
      PGDATA: ${PGDATA}
    entrypoint: [ "postgres" ]
    command: [ "-h", "*", "-c", "shared_buffers=512MB", "-c", "synchronous_commit=off", "-c", "max_connections=200" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h 127.0.0.1 -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
