services:
  postgres-vault-init:
    extends:
      file: ./../postgres/postgres.yaml
      service: postgres-vault-init

  pg-db-init:
    extends:
      file: ./../postgres/postgres.yaml
      service: pg-db-init
    volumes:
      - ram_postgres_data:/var/lib/postgresql/data:rw

  pg-db:
    extends:
      file: ./../postgres/postgres.yaml
      service: pg-db
    depends_on:
      pg-db-init:
        condition: service_completed_successfully
    volumes:
      - ram_postgres_data:/var/lib/postgresql/data:rw

  pg-db-storage-test-init:
    image: postgres:18.4-alpine3.24
    networks:
      - eco-net
    volumes:
      - ram_postgres_data:/var/lib/postgresql/data:rw
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        echo "📡 Testcontainers storage lock container activated..."
        
        echo "⏳ Awaiting primary database initialization and file system creation..."
        while [ ! -f /var/lib/postgresql/data/pgdata/postmaster.pid ]; do
            sleep 0.5
        done
        
        echo "✅ Database initialized. Holding filesystem lock open for handoff..."
        sleep 10
        
        echo "🏁 Handoff completed successfully. Releasing memory volume safety. 🚀"


