package me.neobliz1.ecomonitoring.platform.model.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum EcoPlatformErrorCode {

    UNKNOW_ERROR_CODE("ERR-000000"),

    INVALID_STATION_PAYLOAD("ERR-400001"),
    WEATHER_PACKET_DESERIALIZATION_ERROR("ERR-400002"),
    INVALID_COORDINATES_SQUARE("ERR-400003"),
    INVALID_COORDINATES_BOUNDARIES("ERR-400005"),
    COORDINATES_SQUARE_TOO_LARGE("ERR-400006"),

    WEATHER_MAP_DATA_NOT_FOUND("ERR-404004"),

    PIPELINE_TIMEOUT("ERR-408001"),

    KAFKA_BROKER_DOWN("ERR-500001"),
    REDIS_WINDOW_TIMEOUT("ERR-500002"),
    ENV_FILE_LOAD_FAILED("ERR-500003"),
    REDIS_PASSWORD_NOT_SET("ERR-500004"),
    PROTOCOL_BUFFER_TRANSLATION_ERROR("ERR-500005"),
    SERVICE_INSTANCE_NOT_FOUND("ERR-500006");

    private final String codeStr;
}
