services:
  consul-server:
    image: hashicorp/consul:2.0.0
    ports:
      - "8500:8500"
    networks:
      - eco-net
    healthcheck:
      test: [ "CMD", "consul", "operator", "raft", "list-peers" ]
      interval: 10s       # How often to perform the check
      timeout: 5s         # Max time to allow each check to run
      retries: 3          # Consecutive failures required to report unhealthy
      start_period: 5s    # Grace period to allow boot setup before counting failures
    command: "agent -server -bootstrap-expect=1 -ui -node=control-plane-one -client=0.0.0.0"

  consul-init-service:
    image: hashicorp/consul:2.0.0
    depends_on:
      consul-server:
        condition: service_healthy
    networks:
      - eco-net
    volumes:
      - ./../consul/platform-global-properties.yaml:/tmp/platform-global-properties.yaml:ro
      - ./test-platform-analysis-properties.yaml:/tmp/platform-analysis-properties.yaml:ro
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        echo "📡 Uploading global shared platform properties to Consul KV..."
        GLOBAL_CONTENT=$$(cat /tmp/platform-global-properties.yaml)
        consul kv put -http-addr="http://consul-server:8500" "config/application/data" "$$GLOBAL_CONTENT"

        echo "📡 Uploading service-specific properties for Analysis Service..."
        ANALYSIS_CONTENT=$$(cat /tmp/platform-analysis-properties.yaml)
        consul kv put -http-addr="http://consul-server:8500" "config/eco-monitoring-analysis/data" "$$ANALYSIS_CONTENT"

        echo "✅ All configurations loaded successfully into Consul KV."
  

