spring:
  kafka:
    streams:
      state-dir: /tmp/kafka-streams/analysis-state
      pipeline:
        name:
          aggregation-processor:
            interval: 600 #seconds
          deduplication-processor:
            interval: 5000 #miliseconds
  redis:
    records:
      ttl: 24 #hours