spring:
  kafka:
    streams:
      state-dir: /tmp/kafka-streams/analysis-state
      pipeline:
        name:
          aggregation-processor:
            interval: 5 #seconds
          deduplication-processor:
            interval: 5000 #miliseconds = 5 seconds