services:
  jaeger-tracing:
    # image: jaegertracing/jaeger:2.20.0
    image: jaegertracing/jaeger@sha256:46a886260e04002d8f45e213fc39063fa11a50446048fdaa64786fc0840cb9f8
    user: "65534:65534"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - "16686:16686" # Web UI Dashboard
      - "4317:4317"   # gRPC Trace ingestion (Your Go Gateway and Java microservices send traces here)
      - "4318:4318"   # HTTP Trace ingestion
    networks:
      - eco-net
    environment:
      - METRICS_STORAGE_TYPE=memory
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "16686" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
