spring:
  kafka:
    streams:
      state-dir: /tmp/kafka-streams/analysis-state
      pipeline:
        name:
          aggregation-processor:
            interval: 600 #seconds = 10 minutes
          deduplication-processor:
            interval: 600000 #miliseconds = 10 minutes
  redis:
    records:
      ttl: 24 #hours