services:
  redis-cache:
    image: redis:8.8.0-alpine
    ports:
      - "6379:6379"
    networks:
      - eco-net
    secrets:
      - redis_password
    command: >
      sh -c "redis-server --requirepass \"$$(cat /run/secrets/redis_password)\" --appendonly yes"